$engine: 3
$minFxVersion: 2545
$onesync: on
name: ZenESX Framework
version: 1.0.0
author: Zen Scripts
description: Vollständiges ESX Framework mit ZS Banking, Cayo Perico Integration und Loading Screen

tasks:
  # Download ZenESX Framework
  - action: download_github
    src: https://github.com/zen-scripting/ZenESX-Framework
    ref: main
    dest: ./tmp

  # Move ZenESX Resources
  - action: move_path
    src: ./tmp/loading_screen
    dest: ./resources/loading_screen

  - action: move_path
    src: ./tmp/zs_banking
    dest: ./resources/zs_banking

  - action: move_path
    src: ./tmp/zenesx_update_system
    dest: ./resources/zenesx_update_system

  - action: move_path
    src: ./tmp/zenesx_admin_system
    dest: ./resources/zenesx_admin_system

  - action: move_path
    src: ./tmp/zenesx_performance_monitor
    dest: ./resources/zenesx_performance_monitor

  - action: move_path
    src: ./tmp/zenesx_backup_system
    dest: ./resources/zenesx_backup_system

  - action: move_path
    src: ./tmp/[cayo]
    dest: ./resources/[cayo]

  - action: move_path
    src: ./tmp/zen.sql
    dest: ./zen.sql

  - action: remove_path
    path: ./tmp

  # Download ESX Core (komplette Dateien)
  - action: download_github
    src: https://github.com/esx-framework/esx_core
    ref: main
    dest: ./resources/[esx]

  # Download Dependencies
  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/files/oxmysql.zip
  
  - action: unzip
    src: ./tmp/files/oxmysql.zip
    dest: ./resources/oxmysql

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: master
    dest: ./resources/pma-voice

  # Download ESX Legacy Addons (komplette Dateien)
  - action: download_github
    src: https://github.com/esx-framework/ESX-Legacy-Addons
    ref: main
    dest: ./resources/[esx_addons]

  # Write server.cfg (ESX Core + ZENESX Features)
  - action: write_file
    file: ./server.cfg
    data: |
      # Editable Settings
      # -----------------
      # You can edit the following:
      
      {{serverEndpoints}}
      
      # Set Tags
      sets tags "default, esx, esx legacy, official, roleplay, zenesx"
      
      # Optional Editable Settings
      # --------------------------
      # You may edit the following:
      
      sv_licenseKey "{{svLicense}}"
      sv_hostname "{{serverName}} | ZENESX Framework Server"
      sets sv_projectName " {{serverName}} | [ZENESX Framework]"
      sets sv_projectDesc "{{recipeDescription}}"
      set mysql_connection_string "{{dbConnectionString}}"
      load_server_icon zenesxLogo.png
      sv_maxclients {{maxClients}}
      sets locale "root-AQ" 
      sv_enforceGameBuild 3258
      set resources_useSystemChat true
      
      # System Administrators
      # ---------------------
      # Add system admins
      
      add_principal group.admin group.user
      add_ace group.admin command allow # allow all commands
      add_ace group.admin command.quit deny # but don't allow quit
      add_ace resource.es_extended command.add_ace allow
      add_ace resource.es_extended command.add_principal allow
      add_ace resource.es_extended command.remove_principal allow
      add_ace resource.es_extended command.stop allow
      {{addPrincipalsMaster}}
      
      # pma-voice Config
      # ----------------
      setr voice_enableRadioAnim 1
      setr voice_useNativeAudio true
      setr voice_useSendingRangeOnly true
      
      # security-convars
      # ----------------
      sv_enableNetworkedSounds false
      sv_enableNetworkedScriptEntityStates false
      sv_enableNetworkedPhoneExplosions false
      sv_filterRequestControl 2
      
      # ESX Language (edit to change the language of ESX)
      # -----------------------------------------------------------
      ## Uncomment to set your own locale,
      ## if not, it will use the language you have selected in txAdmin.
      #setr esx:locale "en"
      
      ## Uncomment to owerride the identifier used by ESX.
      ## By default, it uses the language you have selected in txAdmin.
      #setr esx:identifier "license"
      
      # Default & Standalone Resources
      # ------------------------------
      ensure chat
      ensure hardcap
      ensure oxmysql
      
      # ESX Legacy Core
      # ----------
      ensure [core]
      
      # ESX Addons
      # ----------
      ensure [standalone]
      ensure [esx_addons]
      
      # ========================================
      # ZENESX FRAMEWORK FEATURES
      # ========================================
      
      # ZENESX Loading Screen
      ensure loading_screen
      
      # ZENESX Banking System
      ensure zs_banking
      
      # ZENESX Admin System
      ensure zenesx_admin_system
      
      # ZENESX Backup System
      ensure zenesx_backup_system
      
      # ZENESX Performance Monitor
      ensure zenesx_performance_monitor
      
      # ZENESX Update System
      ensure zenesx_update_system
      
      # ========================================
      # ZENESX JOBS SYSTEM
      # ========================================
      
      # RAMAZON Delivery Job
      ensure [jobs]/ramazon_job/rc_ramazon
      ensure [jobs]/ramazon_job/rc_ramazonDelivery
      ensure [jobs]/ramazon_job/rprogress
      ensure [jobs]/ramazon_job/pNotify
      
      # Construction Worker Job
      ensure [jobs]/construction_worker
      
      # ========================================
      # ZENESX PHONE SYSTEM
      # ========================================
      
      # GCPhone - Advanced Smartphone System
      ensure [phone]/gcphone
      ensure [phone]/esx_addons_gcphone
      
      # ========================================
      # ZENESX CAYO PERICO MODS
      # ========================================
      
      # Cayo Perico Resources
      ensure [cayo]/cayo_minimap
      ensure [cayo]/cayo_resources
      ensure [cayo]/cayo_shops
      ensure [cayo]/cayo_gate
      ensure [cayo]/cayo_bridge

variables:
  - name: Database Host
    description: MySQL Database Host
    type: text
    default: localhost

  - name: Database Name
    description: MySQL Database Name
    type: text
    default: zenesx

  - name: Database User
    description: MySQL Database Username
    type: text
    default: root

  - name: Database Password
    description: MySQL Database Password
    type: password
    default: ""

  - name: Server Name
    description: Your FiveM Server Name
    type: text
    default: ZenESX Framework Server

  - name: Max Players
    description: Maximum number of players
    type: number
    default: 32

  - name: Admin Steam ID
    description: Your Steam ID for admin permissions
    type: text
    default: steam:110000000000000