$engine: 3
$minFxVersion: 2545
$onesync: on
name: ZenESX Framework
version: 1.0.0
author: Zen Scripts
description: Vollständiges ESX Framework mit ZS Banking, Cayo Perico Integration, Loading Screen mit Musik und automatischen GitHub Updates

tasks:

  # Download ZenESX Framework
  - action: download_github
    src: https://github.com/zen-scripting/ZenESX-Framework
    ref: main
    dest: ./tmp

  # Database Setup
  - action: move_path
    src: ./tmp/zen.sql
    dest: ./zen.sql

  - action: query_database
    file: ./zen.sql

  # Core ZenESX Resources
  - action: move_path
    src: ./tmp/loading_screen
    dest: ./resources/loading_screen

  - action: move_path
    src: ./tmp/zs_banking
    dest: ./resources/zs_banking

  - action: move_path
    src: ./tmp/zenesx_update_system
    dest: ./resources/zenesx_update_system

  - action: move_path
    src: ./tmp/zenesx_admin_system
    dest: ./resources/zenesx_admin_system

  - action: move_path
    src: ./tmp/zenesx_performance_monitor
    dest: ./resources/zenesx_performance_monitor

  - action: move_path
    src: ./tmp/zenesx_backup_system
    dest: ./resources/zenesx_backup_system

  # Cayo Perico Resources
  - action: move_path
    src: ./tmp/[cayo]
    dest: ./resources/[cayo]

  # Server Configuration
  - action: move_path
    src: ./tmp/server.cfg
    dest: ./server.cfg

  # Download ESX Legacy Core
  - action: download_github
    src: https://github.com/esx-framework/esx_core
    ref: main
    dest: ./resources/[esx]/es_extended

  # Download Dependencies
  - action: download_github
    src: https://github.com/overextended/oxmysql
    ref: main
    dest: ./resources/oxmysql

  - action: download_github
    src: https://github.com/overextended/ox_lib
    ref: main
    dest: ./resources/ox_lib

  - action: download_github
    src: https://github.com/overextended/ox_inventory
    ref: main
    dest: ./resources/ox_inventory

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/pma-voice

  # ESX Jobs
  - action: download_github
    src: https://github.com/esx-framework/esx_policejob
    ref: main
    dest: ./resources/[esx]/esx_policejob

  - action: download_github
    src: https://github.com/esx-framework/esx_ambulancejob
    ref: main
    dest: ./resources/[esx]/esx_ambulancejob

  - action: download_github
    src: https://github.com/esx-framework/esx_mechanicjob
    ref: main
    dest: ./resources/[esx]/esx_mechanicjob

  # ESX Core Scripts
  - action: download_github
    src: https://github.com/esx-framework/esx_society
    ref: main
    dest: ./resources/[esx]/esx_society

  - action: download_github
    src: https://github.com/esx-framework/esx_garage
    ref: main
    dest: ./resources/[esx]/esx_garage

  - action: download_github
    src: https://github.com/esx-framework/esx_shops
    ref: main
    dest: ./resources/[esx]/esx_shops

  # Cleanup
  - action: remove_path
    path: ./tmp

variables:
  - name: Database Host
    description: MySQL Database Host
    type: text
    default: localhost

  - name: Database Name
    description: MySQL Database Name
    type: text
    default: zenesx

  - name: Database User
    description: MySQL Database Username
    type: text
    default: root

  - name: Database Password
    description: MySQL Database Password
    type: password
    default: ""

  - name: Server Name
    description: Your FiveM Server Name
    type: text
    default: ZenESX Framework Server

  - name: Admin Steam ID
    description: Your Steam ID for admin permissions
    type: text
    default: steam:110000000000000

replacements:
  # Database Configuration
  - file: server.cfg
    pattern: 'set mysql_connection_string ".*"'
    value: 'set mysql_connection_string "mysql://{{Database User}}:{{Database Password}}@{{Database Host}}/{{Database Name}}?charset=utf8mb4"'

  # Server Settings
  - file: server.cfg
    pattern: 'sv_hostname ".*"'
    value: 'sv_hostname "{{Server Name}}"'

  # Admin Permissions
  - file: server.cfg
    pattern: 'add_principal identifier.steam:YOUR_STEAM_ID group.admin'
    value: 'add_principal identifier.{{Admin Steam ID}} group.admin'
