$engine: 3
$minFxVersion: 2545
$onesync: on
name: ZenESX Framework
version: 1.1.1.1
author: Zen Scripts
description: Vollständiges ESX Framework mit ZS Banking, Cayo Perico Integration und Loading Screen

tasks:
  # Download ZenESX Framework
  - action: download_github
    src: https://github.com/zen-scripting/ZenESX-Framework
    ref: main
    dest: ./tmp

  # Move ZenESX Resources (bereits im Repository organisiert)
  - action: move_path
    src: ./tmp/[zenesx]
    dest: ./resources/[zenesx]

  - action: move_path
    src: ./tmp/[cayo]
    dest: ./resources/[cayo]

  - action: move_path
    src: ./tmp/[phone]
    dest: ./resources/[phone]

  - action: move_path
    src: ./tmp/zenesxLogo.png
    dest: ./zenesxLogo.png

  - action: move_path
    src: ./tmp/zen.sql
    dest: ./zen.sql

  # Alle Ressourcen werden bereits aus dem ZenESX Repository geladen
  # und sind im [zenesx] Ordner enthalten

  # Server.cfg von ZENESX
  - action: move_path
    src: ./tmp/server.cfg
    dest: ./server.cfg

  # Datenbank importieren
  - action: connect_database
  - action: query_database
    file: ./zen.sql

  ## Cleanup
  - action: remove_path
    path: ./resources/esx_example
  - action: remove_path
    path: ./resources/server.cfg
  - action: remove_path
    path: ./tmp

variables:
  - name: Database Host
    description: MySQL Database Host
    type: text
    default: localhost

  - name: Database Name
    description: MySQL Database Name
    type: text
    default: zenesx

  - name: Database User
    description: MySQL Database Username
    type: text
    default: root

  - name: Database Password
    description: MySQL Database Password
    type: password
    default: ""

  - name: Server Name
    description: Your FiveM Server Name
    type: text
    default: ZenESX Framework Server

  - name: Max Players
    description: Maximum number of players
    type: number
    default: 32

  - name: Admin Steam ID
    description: Your Steam ID for admin permissions
    type: text
    default: steam:110000000000000