$engine: 3
$minFxVersion: 2545
$onesync: on
name: ZenESX Framework
version: 1.0.0
author: Zen Scripts
description: Vollständiges ESX Framework mit ZS Banking, Cayo Perico Integration und Loading Screen

tasks:
  # Download ZenESX Framework
  - action: download_github
    src: https://github.com/zen-scripting/ZenESX-Framework
    ref: main
    dest: ./tmp

  # Move ZenESX Resources
  - action: move_path
    src: ./tmp/loading_screen
    dest: ./resources/loading_screen

  - action: move_path
    src: ./tmp/zs_banking
    dest: ./resources/zs_banking

  - action: move_path
    src: ./tmp/zenesx_update_system
    dest: ./resources/zenesx_update_system

  - action: move_path
    src: ./tmp/zenesx_admin_system
    dest: ./resources/zenesx_admin_system

  - action: move_path
    src: ./tmp/zenesx_performance_monitor
    dest: ./resources/zenesx_performance_monitor

  - action: move_path
    src: ./tmp/zenesx_backup_system
    dest: ./resources/zenesx_backup_system

  - action: move_path
    src: ./tmp/[cayo]
    dest: ./resources/[cayo]

  - action: move_path
    src: ./tmp/zen.sql
    dest: ./zen.sql

  - action: remove_path
    path: ./tmp

  # Import Database (nach dem Verschieben der Dateien)
  - action: connect_database
    connection_string: "mysql://{{Database User}}:{{Database Password}}@{{Database Host}}/{{Database Name}}?charset=utf8mb4"
  
  - action: query_database
    connection_string: "mysql://{{Database User}}:{{Database Password}}@{{Database Host}}/{{Database Name}}?charset=utf8mb4"
    file: ./zen.sql

  # Download ESX Core
  - action: download_github
    src: https://github.com/esx-framework/esx_core
    ref: main
    dest: ./resources/[esx]/esx_core

  # Download Dependencies
  - action: download_github
    src: https://github.com/overextended/oxmysql
    ref: main
    dest: ./resources/oxmysql

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: master
    dest: ./resources/pma-voice

  # Download ESX Legacy Addons
  - action: download_github
    src: https://github.com/esx-framework/ESX-Legacy-Addons
    ref: main
    dest: ./resources/[esx_addons]

  # ESX Core Scripts sind bereits in ESX-Legacy-Addons enthalten
  # Keine separaten Downloads nötig

  # Write server.cfg
  - action: write_file
    file: ./server.cfg
    data: |
      sv_hostname "{{Server Name}}"
      sv_maxclients {{Max Players}}
      set mysql_connection_string "mysql://{{Database User}}:{{Database Password}}@{{Database Host}}/{{Database Name}}?charset=utf8mb4"
      set onesync on
      sv_licenseKey "YOUR_LICENSE_KEY_HERE"
      ensure loading_screen
      ensure zs_banking
      ensure zenesx_update_system
      ensure zenesx_admin_system
      ensure zenesx_performance_monitor
      ensure zenesx_backup_system
      ensure "[cayo]/cayo minimap"
      ensure "[cayo]/cayo resurces"
      ensure "[cayo]/cayo shops"
      ensure "[cayo]/cayo tor"
      ensure "[cayo]/Cayo_Bridge"
      ensure esx_core
      ensure oxmysql
      ensure pma-voice
      ensure "[esx_addons]"
      add_principal identifier.{{Admin Steam ID}} group.admin
      add_ace group.admin command allow
      add_ace group.admin command.quit deny
      add_ace resource.es_extended command.add_ace allow
      add_ace resource.es_extended command.add_principal allow

variables:
  - name: Database Host
    description: MySQL Database Host
    type: text
    default: localhost

  - name: Database Name
    description: MySQL Database Name
    type: text
    default: zenesx

  - name: Database User
    description: MySQL Database Username
    type: text
    default: root

  - name: Database Password
    description: MySQL Database Password
    type: password
    default: ""

  - name: Server Name
    description: Your FiveM Server Name
    type: text
    default: ZenESX Framework Server

  - name: Max Players
    description: Maximum number of players
    type: number
    default: 32

  - name: Admin Steam ID
    description: Your Steam ID for admin permissions
    type: text
    default: steam:110000000000000