$engine: 3
$minFxVersion: 2545
$onesync: on
name: ZenESX Framework
version: 1.1.1.1
author: Zen Scripts
description: Vollständiges ESX Framework mit ZS Banking, Cayo Perico Integration und Loading Screen

tasks:
  # Download ZenESX Framework
  - action: download_github
    src: https://github.com/zen-scripting/ZenESX-Framework
    ref: main
    dest: ./tmp

  # Move ZenESX Resources (bereits im Repository organisiert)
  - action: move_path
    src: ./tmp/[zenesx]
    dest: ./resources/[zenesx]

  - action: move_path
    src: ./tmp/[cayo]
    dest: ./resources/[cayo]

  - action: move_path
    src: ./tmp/[phone]
    dest: ./resources/[phone]

  - action: move_path
    src: ./tmp/zenesxLogo.png
    dest: ./zenesxLogo.png

  - action: move_path
    src: ./tmp/zen.sql
    dest: ./zen.sql

  # Download ESX Core (nur der Link, keine Dateien)
  # Die Core wird über den Link geladen: https://github.com/esx-framework/esx_core/tree/main/%5Bcore%5D

  # Download Dependencies
  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/files/oxmysql.zip
  
  - action: unzip
    src: ./tmp/files/oxmysql.zip
    dest: ./resources/oxmysql

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: 4754a4dfff1e897f14df6d7d0e06c7fbfbaa20d5
    dest: ./resources/pma-voice

  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  # Server.cfg von ZENESX
  - action: move_path
    src: ./tmp/server.cfg
    dest: ./server.cfg

  # Datenbank importieren
  - action: connect_database
  - action: query_database
    file: ./zen.sql

  # Download basic resources and ESX dependencies
  - action: download_github
    src: https://github.com/esx-framework/esx-legacy
    ref: 8153f6a9221baeef0affb0176e5811007b8f5e3b
    dest: ./resources/[esx_addons]

  # Download EasyAdmin (Admin System) in [zenesx] Ordner
  - action: download_github
    src: https://github.com/Blumlaut/EasyAdmin
    ref: 776ac8f3898182e5c075d533bbd89e92efa017e9
    dest: ./resources/[zenesx]/EasyAdmin

  # Download MDT (Mobile Data Terminal)
  - action: download_github
    src: https://github.com/thelindat/mdt
    ref: 0c804de3cd497d70d8ae76bf1699d76d4c9d94fc
    dest: ./resources/mdt

  ## Cleanup
  - action: remove_path
    path: ./resources/esx_example
  - action: remove_path
    path: ./resources/server.cfg
  - action: remove_path
    path: ./resources/[esx_addons]/esx_whitelist
  - action: remove_path
    path: ./resources/[esx_addons]/esx_voice
  - action: remove_path
    path: ./resources/[esx_addons]/esx_phone
  - action: remove_path
    path: ./tmp

  # Download ESX Legacy Addons (nur der Link, keine Dateien)
  # Die Addons werden über den Link geladen: https://github.com/esx-framework/ESX-Legacy-Addons/tree/main/%5Besx_addons%5D

  # Server.cfg wird manuell konfiguriert

variables:
  - name: Database Host
    description: MySQL Database Host
    type: text
    default: localhost

  - name: Database Name
    description: MySQL Database Name
    type: text
    default: zenesx

  - name: Database User
    description: MySQL Database Username
    type: text
    default: root

  - name: Database Password
    description: MySQL Database Password
    type: password
    default: ""

  - name: Server Name
    description: Your FiveM Server Name
    type: text
    default: ZenESX Framework Server

  - name: Max Players
    description: Maximum number of players
    type: number
    default: 32

  - name: Admin Steam ID
    description: Your Steam ID for admin permissions
    type: text
    default: steam:110000000000000